# BEGIN_KITTY_THEME
# Tokyo Night Storm
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="Maple Mono NF"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#

tab_bar_style powerline
tab_bar_edge top

map ctrl+alt+enter launch --cwd=current

map ctrl+v paste_from_clipboard

cursor_blink_interval -1

enable_audio_bell no

confirm_os_window_close 0

shell_integration no-title
tab_title_template "{index}: {bwd}"
active_tab_title_template "[{index}]: {bwd}"
window_title_template "{title}"
